surName = str(input("surname: "))
firstName = str(input("first name: "))
street = str(input("street: "))
number = int(input("number: "))
zipCode = int(input("zip code: "))
city = str(input("city: "))

print(firstName, surName)
print(street, number)
print(zipCode, city)
